import pitBullE from "./../assets/NFTs/legendary/pitbull-l.png";
import pastorAlemanL from "./../assets/NFTs/epic/gsheperd-e.png";
import gRetrieverC from "./../assets/NFTs/common/gretriever-c.png";
import sinuR from "./../assets/NFTs/rare/sinu-r.png";
import dobermanM from "./../assets/NFTs/mythical/doberman-m.png";
import dalmatianSR from "./../assets/NFTs/superrare/dalmatian-sr.png";
//Note: this mockup data was intended to show the currents NFTs you have, usually people don't have this many.
export const Nfts = [
  {
    id: 1,
    imageUrl: pastorAlemanL,
    s1: 73,
    s2: 45,
    s3: 45,
    s4: 45,
    s5: 46,
    rarity: "ÉPICO",
    energyleft: "334",
    name: "PASTOR ALEMÁN",
  },
  {
    id: 2,
    imageUrl: gRetrieverC,
    s1: 23,
    s2: 65,
    s3: 15,
    s4: 25,
    s5: 66,
    rarity: "COMÚN",
    energyleft: "550",
    name: "GOLDEN RETRIEVER",
  },
  {
    id: 3,
    imageUrl: pitBullE,
    s1: 72,
    s2: 25,
    s3: 35,
    s4: 100,
    s5: 26,
    rarity: "LEGENDARIO",
    energyleft: "124",
    name: "PITBULL",
  },
  {
    id: 4,
    imageUrl: sinuR,
    s1: 72,
    s2: 25,
    s3: 35,
    s4: 100,
    s5: 26,
    rarity: "RARO",
    energyleft: "324",
    name: "SHIBA INU",
  },
  {
    id: 5,
    imageUrl: dobermanM,
    s1: 74,
    s2: 45,
    s3: 25,
    s4: 95,
    s5: 36,
    rarity: "MÍTICO",
    energyleft: "034",
    name: "DOBERMAN",
  },
  {
    id: 6,
    imageUrl: dalmatianSR,
    s1: 72,
    s2: 25,
    s3: 35,
    s4: 100,
    s5: 26,
    rarity: "SUPER RARO",
    energyleft: "124",
    name: "DÁLMATA",
  },
];
